### ISSUE TITLE
Bug: The end keyword is not escaped in generated codedom

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.Compiler.CodeDom#10]
See: https://bugzilla.xamarin.com/show_bug.cgi?id=24709 for detail.

**Comment by dsyme** [comment]
Looks like the fix is just to add ``end`` here: https://github.com/fsprojects/FSharp.Compiler.CodeDom/blob/master/src/FSharp.Compiler.CodeDom/CleanCodeDomGenerator.fs#L214

Also in CodeDomGenerator.fs

**Comment by drvink** [comment]
Isn't `end` already there? Am I missing something?

I've made a standalone repro for this that doesn't require Android Studio or the Xamarin stuff.

```fsharp
#light "off"

open System
open System.IO
open System.CodeDom
open FSharp.Compiler.CodeDom

[<EntryPoint>]
let main argv =
  use provider = new FSharpCodeProvider() in
  let ccu = CodeCompileUnit() in
  let nsp = CodeNamespace("MyNamespace") in
  let ty = CodeTypeDeclaration("MyClass") in
  let meth =
    CodeMemberMethod(
      Name="Main",
      Attributes=MemberAttributes.Static) in
  let ret_ty = CodeTypeReference(typeof<Int32>) in
  meth.ReturnType <- ret_ty;

  let ty2 = CodeTypeDeclaration("hober") in
  let prop =
    CodeMemberProperty(
      Name="end",
      Type=CodeTypeReference(typeof<int>),
      Attributes=MemberAttributes.Static) in
  let retst = CodeMethodReturnStatement(CodePrimitiveExpression(0)) in
  ignore (prop.GetStatements.Add(retst));
  ignore (ty2.Members.Add(prop));

  let early_return =
    let test =
      CodeBinaryOperatorExpression(
        CodePropertyReferenceExpression(
          CodeTypeReferenceExpression("hober"),
          "end"),
        CodeBinaryOperatorType.ValueEquality,
        CodePropertyReferenceExpression(
          CodeTypeReferenceExpression("hober"),
          "end")) in
    let if_true =
      CodeMethodReturnStatement(CodePrimitiveExpression(0))
      :> CodeStatement in
    let if_false =
      CodeExpressionStatement(
        CodeMethodInvokeExpression(
          CodeMethodReferenceExpression(
            CodeTypeReferenceExpression(typeof<Console>), "WriteLine"),
          CodePrimitiveExpression(@"hi")))
      :> CodeStatement in
    CodeConditionStatement(test, [| if_true |], [| if_false |]) in
  ignore (meth.Statements.Add(early_return));
  ignore (meth.Statements.Add(
            CodeMethodReturnStatement(CodePrimitiveExpression(1))));
  ignore (ty.Members.Add(meth));
  ignore (nsp.Types.Add(ty2));
  ignore (nsp.Types.Add(ty));
  ignore (ccu.Namespaces.Add(nsp));
  let opts = Compiler.CodeGeneratorOptions() in
  use sw = new StringWriter() in
  provider.GenerateCodeFromCompileUnit(ccu, sw, opts);
  printfn "%A" (sw.ToString());
  (*
  let res = provider.CompileAssemblyFromDom(
    Compiler.CompilerParameters(),
    [|ccu|]) in
  if res.Errors.HasErrors then
    for err in res.Errors do printfn "%s" err.ErrorText done
  else ();
  *)
  0
```

**Comment by dsyme** [comment]
Hmm... Yes, it is there.  I wonder what the issue is

**Comment by dsyme** [comment]
It would be great to get this fixed - it was reported to Xamarin ages ago but the bug report only just got added here

**Comment by drvink** [comment]
PR: #12

@dsyme This fixes the issue, though I wonder: should we continue to use the current behavior (prefix "_" to clashing names), or should we use the `` escape mechanism? I think the latter is preferable--consider the case where a name is reserved in F# but not in some other language and the user is trying to reference it via some CodeDom-generated code--but it will be a breaking change.

**Comment by dsyme** [comment]
Using ``xyz`` is preferable. I don't know why it's not being used, it's possible this code actually predates the addition of that to the language (Tomas Petricek wrote it in his very first internship I think!)

**Comment by drvink** [comment]
It just occurred to me that CodeDom providers are supposed to supply two different escape mechanisms: [CreateEscapedIdentifier](https://msdn.microsoft.com/EN-US/library/4sa8yc1e%28v=VS.110,d=hv.2%29.aspx) and [CreateValidIdentifier](https://msdn.microsoft.com/EN-US/library/2t77wy53%28v=VS.110,d=hv.2%29.aspx). We do, but we currently have them backwards, at least according to what the documentation seems to say each one should do, so I'll fix that too while I'm at it.

**Comment by drvink** [comment]
Fixed. I'll try to make a new release and push it to NuGet later today.
