### ISSUE TITLE
Work on mono (Linux)

### ISSUE THREAD

**Issue by iskiselev** [fsprojects/FSharp.Compiler.CodeDom#8]
It is impossible currently to run it with Mono on Linux.
When .Net exe should be executed on Mono, Process.StartInfo.FileName should be "mono" and real executable name should be passed as first argument.
It would be also great if there would be possibility to pass fsc.exe through environment variable if it was not found in registry - it will give option to use FSharp.Compiler.Tools nuget package.

**Comment by iskiselev** [comment]
Really, the only that should be done to allow work on linux - read path from some environment variable if it was not found in registry. If Process.StartInfo.FileName is *.exe file name, it should be full name with path.

**Comment by iskiselev** [comment]
It would be even possible to workaround and provide some value from "registry" if in CompilerLocationUtils.fs will not be used P/Invoke and will be used reading from Wow6432Node node instead.

Next example use both solutions:
```
namespace Internal.Utilities
open System
open System.Runtime.InteropServices

module internal FSharpEnvironment =

    // The F# team version number. This version number is used for
    //     - the F# version number reported by the fsc.exe and fsi.exe banners in the CTP release
    //     - the F# version number printed in the HTML documentation generator
    //     - the .NET DLL version number for all VS2008 DLLs
    //     - the VS2008 registry key, written by the VS2008 installer
    //         HKEY_LOCAL_MACHINE\Software\Microsoft\.NETFramework\AssemblyFolders\Microsoft.FSharp-" + FSharpTeamVersionNumber
    // Also
    //     - for Beta2, the language revision number indicated on the F# language spec
    //
    // It is NOT the version number listed on FSharp.Core.dll
    let FSharpTeamVersionNumber = "1.9.9.9"

    module Option =
        /// Convert string into Option string where null and String.Empty result in None
        let ofString s =
            if String.IsNullOrEmpty s then None
            else Some s

    let tryRegKey(subKey:string) =
        Option.ofString
            (try
                downcast Microsoft.Win32.Registry.GetValue("HKEY_LOCAL_MACHINE\\"+subKey,null,null)
             with e->
                System.Diagnostics.Debug.Assert(false, sprintf "Failed in GetDefaultRegistryStringValueViaDotNet: %s" (e.ToString()))
                null)

    let BinFolderOfDefaultFSharpCompiler =
        try
            let key31wow = @"Software\Wow6432Node\Microsoft\FSharp\3.1\Runtime\v4.0"
            let key30wow = @"Software\Wow6432Node\Microsoft\FSharp\3.0\Runtime\v4.0"
            let key20wow = @"Software\Wow6432Node\Microsoft\FSharp\2.0\Runtime\v4.0"
            let key31 = @"Software\Microsoft\FSharp\3.1\Runtime\v4.0"
            let key30 = @"Software\Microsoft\FSharp\3.0\Runtime\v4.0"
            let key20 = @"Software\Microsoft\FSharp\2.0\Runtime\v4.0"

            match tryRegKey key31 with
            | Some r ->  Some r
            | None ->
            match tryRegKey key31wow with
            | Some r ->  Some r
            | None ->
            match tryRegKey key30 with
            | Some r ->  Some r
            | None ->
            match tryRegKey key30wow with
            | Some r ->  Some r
            | None ->
            match tryRegKey key20 with
            | Some r ->  Some r
            | None ->
            match tryRegKey key20wow with
            | Some r ->  Some r
            | None ->
            Option.ofString(Environment.GetEnvironmentVariable("FSharpPath"))
        with _ ->
            System.Diagnostics.Debug.Assert(false, "Error while determining default location of F# compiler")
            None

```

**Comment by drvink** [comment]
That looks fine to me. I'm not sure why the code currently uses different paths depending on whether the system is 32 or 64-bit, because it seems that querying explicitly under `Wow6432Node` using the .NET function works fine. Before I break something, @tpetricek, do you remember why the code is the way it currently is?

**Comment by iskiselev** [comment]
If nobody could verify safety of registry querying using manged code, could we at least add using of environment variable as last option?
Should I create PR?

**Comment by drvink** [comment]
Sorry for the delay. I'll commit your suggested change in a moment. Given that the existing code references how Windows 2000 and earlier behaved (!) and that it seems to work fine with the modified code, I think it's safe to modify.

We'll use `FSHARPINSTALLDIR` as the environment variable, since that's what's used by Visual Studio as well.

**Comment by drvink** [comment]
Added with fsprojects/FSharp.Compiler.CodeDom#9.

**Comment by iskiselev** [comment]
Where could I hope to see fixed version on nuget?

**Comment by dsyme** [comment]
@drvink Can you push a new package to nuget?
